// apps/docs/src/components/react/PhoneField.tsx
import { useState } from 'react';
import {
  getCallingCode,
  getDialCode,
  searchCountries,
  type Country,
} from 'country-kit';
import { FlagThumb } from './FlagThumb';

export default function PhoneField() {
  const [query, setQuery] = useState('Anguilla');
  const [national, setNational] = useState('4971234');
  const matches = searchCountries(query, { limit: 5 });
  const [picked, setPicked] = useState<Country | undefined>(matches[0]);
  const country = picked ?? matches[0];
  const prefix = country ? (getDialCode(country.code) ?? '') : '';
  const e164 = country ? (getCallingCode(country.code) ?? '') : '';

  return (
    <div className="ck-widget">
      <label className="ck-label" htmlFor="react-phone-q">
        Find a country
      </label>
      <input
        id="react-phone-q"
        className="ck-input"
        value={query}
        onChange={(event) => {
          setQuery(event.target.value);
          setPicked(undefined);
        }}
        placeholder="Anguilla, +1, United States…"
      />
      <ul className="ck-hits">
        {matches.length ? (
          matches.map((item) => (
            <li key={item.code}>
              <button
                type="button"
                className={`ck-hit ${country?.code === item.code ? 'is-active' : ''}`}
                onClick={() => setPicked(item)}
              >
                <FlagThumb code={item.code} className="h-5 w-7 shrink-0" />
                <span className="min-w-0 flex-1 truncate">{item.commonName}</span>
                <span className="font-mono text-xs text-[var(--muted)]">
                  {item.dialCode}
                </span>
              </button>
            </li>
          ))
        ) : (
          <li className="ck-empty">
            No countries match. Try a name, ISO code, or calling prefix such as +1.
          </li>
        )}
      </ul>
      <div className="ck-row mt-4">
        <p className="shrink-0 font-mono text-lg">{prefix || '—'}</p>
        <input
          className="ck-input"
          inputMode="tel"
          value={national}
          onChange={(event) => setNational(event.target.value.replace(/\D/g, ''))}
          placeholder="National number"
          aria-label="National number"
        />
      </div>
      {country ? (
        <dl className="ck-dl">
          <dt>Display</dt>
          <dd>
            {prefix}
            {national || '…'}
          </dd>
          <dt>E.164 country</dt>
          <dd>{e164}</dd>
          <dt>NANP</dt>
          <dd>{country.nanpAreaCodes?.join(', ') ?? '—'}</dd>
        </dl>
      ) : null}
    </div>
  );
}

// apps/docs/src/components/vue/PhoneField.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  getCallingCode,
  getDialCode,
  getFlagSvgUrl,
  searchCountries,
  type Country,
} from 'country-kit';

const query = ref('Anguilla');
const national = ref('4971234');
const picked = ref<Country | undefined>();
const matches = computed(() => searchCountries(query.value, { limit: 5 }));
const country = computed(() => picked.value ?? matches.value[0]);
const prefix = computed(() =>
  country.value ? (getDialCode(country.value.code) ?? '') : '',
);
const e164 = computed(() =>
  country.value ? (getCallingCode(country.value.code) ?? '') : '',
);

function onQuery(value: string) {
  query.value = value;
  picked.value = undefined;
}
</script>

<template>
  <div class="ck-widget">
    <label class="ck-label" for="vue-phone-q">Find a country</label>
    <input
      id="vue-phone-q"
      class="ck-input"
      :value="query"
      placeholder="Anguilla, +1, United States…"
      @input="onQuery(($event.target as HTMLInputElement).value)"
    />
    <ul class="ck-hits">
      <li v-for="item in matches" :key="item.code">
        <button
          type="button"
          class="ck-hit"
          :class="{ 'is-active': country?.code === item.code }"
          @click="picked = item"
        >
          <span class="flag-frame h-5 w-7 shrink-0">
            <img :src="getFlagSvgUrl(item.code)" alt="" />
          </span>
          <span class="min-w-0 flex-1 truncate">{{ item.commonName }}</span>
          <span class="font-mono text-xs text-[var(--muted)]">{{ item.dialCode }}</span>
        </button>
      </li>
      <li v-if="!matches.length" class="ck-empty">
        No countries match. Try a name, ISO code, or calling prefix such as +1.
      </li>
    </ul>
    <div class="ck-row mt-4">
      <p class="shrink-0 font-mono text-lg">{{ prefix || '—' }}</p>
      <input
        class="ck-input"
        inputmode="tel"
        :value="national"
        placeholder="National number"
        aria-label="National number"
        @input="national = ($event.target as HTMLInputElement).value.replace(/\D/g, '')"
      />
    </div>
    <dl v-if="country" class="ck-dl">
      <dt>Display</dt>
      <dd>{{ prefix }}{{ national || '…' }}</dd>
      <dt>E.164 country</dt>
      <dd>{{ e164 }}</dd>
      <dt>NANP</dt>
      <dd>{{ country.nanpAreaCodes?.join(', ') ?? '—' }}</dd>
    </dl>
  </div>
</template>
