// apps/docs/src/components/react/ResidenceSelect.tsx
import { useMemo, useState } from 'react';
import { getCountry, getCountrySelectOptions } from 'country-kit';
import { FlagThumb } from './FlagThumb';

export default function ResidenceSelect() {
  const options = useMemo(
    () => getCountrySelectOptions({ independent: true }),
    [],
  );
  const [code, setCode] = useState('FR');
  const country = getCountry(code);

  return (
    <div className="ck-widget">
      <label className="ck-label" htmlFor="react-residence">
        Country of residence
      </label>
      <div className="ck-row">
        <FlagThumb code={code} />
        <select
          id="react-residence"
          className="ck-select"
          value={code}
          onChange={(event) => setCode(event.target.value)}
        >
          {options.map((option) => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </select>
      </div>
      {country ? (
        <dl className="ck-dl">
          <dt>Store</dt>
          <dd>{country.code}</dd>
          <dt>ISO name</dt>
          <dd>{country.name}</dd>
          <dt>TLD</dt>
          <dd>{country.tld ?? '—'}</dd>
          <dt>Currency</dt>
          <dd>{country.currencies.join(', ') || '—'}</dd>
        </dl>
      ) : null}
    </div>
  );
}

// apps/docs/src/components/vue/ResidenceSelect.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { getCountry, getCountrySelectOptions, getFlagSvgUrl } from 'country-kit';

const options = getCountrySelectOptions({ independent: true });
const code = ref('FR');
const country = computed(() => getCountry(code.value));
const flag = computed(() => getFlagSvgUrl(code.value));
</script>

<template>
  <div class="ck-widget">
    <label class="ck-label" for="vue-residence">Country of residence</label>
    <div class="ck-row">
      <span class="flag-frame h-8 w-11 shrink-0">
        <img v-if="flag" :src="flag" alt="" />
      </span>
      <select id="vue-residence" v-model="code" class="ck-select">
        <option v-for="option in options" :key="option.value" :value="option.value">
          {{ option.label }}
        </option>
      </select>
    </div>
    <dl v-if="country" class="ck-dl">
      <dt>Store</dt>
      <dd>{{ country.code }}</dd>
      <dt>ISO name</dt>
      <dd>{{ country.name }}</dd>
      <dt>TLD</dt>
      <dd>{{ country.tld ?? '—' }}</dd>
      <dt>Currency</dt>
      <dd>{{ country.currencies.join(', ') || '—' }}</dd>
    </dl>
  </div>
</template>
