// apps/docs/src/components/vue/CodeValidator.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { getCountry, isValidCallingCode, isValidCountryCode } from 'country-kit';

const samples = ['US', 'usa', '840', 'GB', 'XK', 'XX'];
const raw = ref('USA');
const payload = computed(() => {
  const country = getCountry(raw.value);
  return {
    isValidCountryCode: isValidCountryCode(raw.value),
    resolved: country
      ? { code: country.code, commonName: country.commonName }
      : null,
    isValidCallingCode: isValidCallingCode(
      raw.value.startsWith('+') ? raw.value : `+${raw.value}`,
    ),
  };
});
</script>

<template>
  <div class="ck-widget">
    <label class="ck-label" for="vue-validate">Code from a query param</label>
    <input id="vue-validate" v-model="raw" class="ck-input font-mono" />
    <div class="mt-3 flex flex-wrap gap-2">
      <button
        v-for="sample in samples"
        :key="sample"
        type="button"
        class="ck-chip font-mono"
        @click="raw = sample"
      >
        {{ sample }}
      </button>
    </div>
    <pre class="mt-4 overflow-x-auto rounded-xl bg-[#161412] p-3 font-mono text-xs text-[#f4efe6]">{{
      JSON.stringify(payload, null, 2)
    }}</pre>
  </div>
</template>

// apps/docs/src/components/react/CodeValidator.tsx
import { useState } from 'react';
import { getCountry, isValidCallingCode, isValidCountryCode } from 'country-kit';

const samples = ['US', 'usa', '840', 'GB', 'XK', 'XX'];

export default function CodeValidator() {
  const [raw, setRaw] = useState('USA');
  const country = getCountry(raw);
  const payload = {
    isValidCountryCode: isValidCountryCode(raw),
    resolved: country
      ? { code: country.code, commonName: country.commonName }
      : null,
    isValidCallingCode: isValidCallingCode(raw.startsWith('+') ? raw : `+${raw}`),
  };

  return (
    <div className="ck-widget">
      <label className="ck-label" htmlFor="react-validate">
        Code from a query param
      </label>
      <input
        id="react-validate"
        className="ck-input font-mono"
        value={raw}
        onChange={(event) => setRaw(event.target.value)}
      />
      <div className="mt-3 flex flex-wrap gap-2">
        {samples.map((sample) => (
          <button
            key={sample}
            type="button"
            className="ck-chip font-mono"
            onClick={() => setRaw(sample)}
          >
            {sample}
          </button>
        ))}
      </div>
      <pre className="mt-4 overflow-x-auto rounded-xl bg-[#161412] p-3 font-mono text-xs text-[#f4efe6]">
        {JSON.stringify(payload, null, 2)}
      </pre>
    </div>
  );
}
